name: Build ARM64 image

on:
  workflow_dispatch:
  repository_dispatch:   # Esto lo disparará Bitbucket

jobs:
  build-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (opcional)
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push ARM64 image
        run: |
          docker buildx build \
            --platform linux/arm64 \
            -t ${{ secrets.DOCKERHUB_USER }}/back_black_room:v1 \
            --push .
